DATASET:
  NAME: "CIFAR100MD"
  USERS: 20
  SOURCE_DOMAINS: ["client_0", "client_1", "client_2", "client_3", "client_4"]
  USE_PERCENT_PARTITION: False
  BETA: 0.3

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 256
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.5071, 0.4867, 0.4408]
  PIXEL_STD: [0.2675, 0.2565, 0.2761]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.001
  ROUND: 50
  MAX_EPOCH: 1
  LR_SCHEDULER: "single_step"
  WARMUP_EPOCH: 0
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
