DATASET:
  NAME: "TinyImageNetMD"
  USERS: 5
  SOURCE_DOMAINS: ["client_0", "client_1", "client_2", "client_3", "client_4"]
  DOMAIN_P: 1.0

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 256
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.4802, 0.4481, 0.3975]
  PIXEL_STD: [0.2302, 0.2265, 0.2262]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.001
  ROUND: 50
  MAX_EPOCH: 1
  LR_SCHEDULER: "single_step"
  WARMUP_EPOCH: 0
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
